@endpoint = https://khdbfr661j.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###
 
POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "location": "Toronto",
  "name": "So-So"
}
###

GET {{endpoint}}/spaces?spaceId=057d5b72-a263-4f67-921d-5028af49c036
###

GET {{endpoint}}/spaces?location=Toronto
###